import argparse
import mimetypes
import os
import smtplib
from email.message import EmailMessage
from pathlib import Path

from jinja2 import Template

from src.daily_summary import build_daily_summary
from src.email_attachments import write_watchlist_csv


EMAIL_TEMPLATE = Template(
"""Good morning,

Here is your sealed product pricing snapshot for {{ date }} (last {{ window_hours }} hours).

Best current in-stock offers by set:
{% if best_by_set %}
{% for row in best_by_set %}
- {{ row.set_name }} | {{ row.product_type }} | {{ row.best_site }} @ ${{ '%.2f'|format(row.best_price) }}
  Price/Pack: {% if row.best_price_per_pack is not none %}${{ '%.4f'|format(row.best_price_per_pack) }}{% else %}n/a{% endif %}
  Buy: {{ row.best_url }}
{% endfor %}
{% else %}
- No in-stock winners found in the last {{ window_hours }} hours
{% endif %}

In-stock price drops (>= {{ drop_pct_threshold }}%):
{% if drops %}
{% for drop in drops %}
- {{ drop.set_name }} | {{ drop.product_type }} | {{ drop.site_name }}: ${{ '%.2f'|format(drop.latest_price) }} ({{ drop.pct_change_price }}%)
  Price/Pack: {% if drop.latest_price_per_pack is not none %}${{ '%.4f'|format(drop.latest_price_per_pack) }}{% else %}n/a{% endif %}
  Buy: {{ drop.sku_or_url }}
{% endfor %}
{% else %}
- None found
{% endif %}

Market movers:
Rising: {{ num_rising }} | Falling: {{ num_falling }} | In-Stock SKUs tracked: {{ in_stock_count }}
{% if top_movers %}
{% for mover in top_movers[:10] %}
- {{ mover.set_name }} | {{ mover.product_type }} | {{ mover.site_name }}: {{ mover.pct_change_price }}% (latest ${{ '%.2f'|format(mover.latest_price) }})
{% endfor %}
{% else %}
- Not enough history yet
{% endif %}

Generated by PriceChecker
"""
)


def parse_args():
    parser = argparse.ArgumentParser(description="Send the daily pricing summary email.")
    parser.add_argument("--db", default=os.environ.get("PRICECHECK_DB_PATH", "results/history.sqlite"))
    parser.add_argument("--sender", default=os.environ.get("EMAIL_SENDER", "jsquaredvendingokc@gmail.com"))
    parser.add_argument("--recipient", default=os.environ.get("EMAIL_RECIPIENT", "jsquaredvendingokc@gmail.com"))
    parser.add_argument("--drop-threshold", type=float, default=float(os.environ.get("DROP_PCT_THRESHOLD", "10.0")))
    return parser.parse_args()


def send_gmail(sender: str, recipient: str, subject: str, body: str, attachments=None) -> None:
    app_password = os.environ.get("GMAIL_APP_PASSWORD")
    if not app_password:
        raise RuntimeError("Missing env var GMAIL_APP_PASSWORD (Gmail App Password).")

    message = EmailMessage()
    message["From"] = sender
    message["To"] = recipient
    message["Subject"] = subject
    message.set_content(body)

    for file_path in attachments or []:
        path = Path(file_path)
        if not path.exists():
            continue
        content_type, _encoding = mimetypes.guess_type(str(path))
        if not content_type:
            content_type = "application/octet-stream"
        maintype, subtype = content_type.split("/", 1)
        with open(path, "rb") as handle:
            message.add_attachment(handle.read(), maintype=maintype, subtype=subtype, filename=path.name)

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(sender, app_password)
        smtp.send_message(message)


def main():
    args = parse_args()

    db_path = Path(args.db)
    results_dir = db_path.parent
    results_dir.mkdir(parents=True, exist_ok=True)

    summary = build_daily_summary(
        db_path=str(db_path),
        drop_pct_threshold=args.drop_threshold,
    )

    body = EMAIL_TEMPLATE.render(
        date=summary["date_local_label"],
        window_hours=summary["window_hours"],
        drop_pct_threshold=summary["drop_pct_threshold"],
        drops=summary["drops"],
        best_by_set=summary["best_by_set"],
        top_movers=summary["top_movers"],
        num_rising=summary["num_rising"],
        num_falling=summary["num_falling"],
        in_stock_count=summary["in_stock_count"],
    )

    attachments = []
    if summary.get("drops"):
        watchlist_path = results_dir / f"watchlist_drops_{summary['date_local_label']}.csv"
        write_watchlist_csv(str(watchlist_path), summary["drops"])
        attachments.append(str(watchlist_path))

    subject = f"PriceChecker Daily Summary - {summary['date_local_label']}"
    send_gmail(args.sender, args.recipient, subject, body, attachments=attachments)
    print("Daily summary email sent.")
    if attachments:
        print(f"Attached: {attachments}")


if __name__ == "__main__":
    main()
